USE jwtpracdb;

DROP TABLE IF EXISTS USERDB CASCADE;

CREATE TABLE IF NOT EXISTS USERDB
(
    USER_CODE INT AUTO_INCREMENT,
    USER_ID VARCHAR(255),
    USER_PASS VARCHAR(255),
    USER_NAME VARCHAR(255),
    USER_ROLE  VARCHAR(255),
    CONSTRAINT pk_category_code PRIMARY KEY (USER_CODE)
) ENGINE=INNODB;