spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwtpracdb

mybatis:
  mapper-locations: mapper/**/*.xml

jwt:
  key: dkananswkdufdlqslek!
  time: 86400000